Update ps_run.yaml

diff --git a/.github/workflows/ps_run.yaml b/.github/workflows/ps_run.yaml
--- a/.github/workflows/ps_run.yaml
+++ b/.github/workflows/ps_run.yaml
@@ -8,9 +8,15 @@ jobs:
       - name: Checkout repository
         uses: actions/checkout@v3
       - name: Set up PowerShell
-        uses: actions/setup-powershell@v1
+        uses: actions/setup-powershell@v2
       - name: Run PowerShell Script
-        run: |
-          write-host "PowerShell script invoked and get executed as well..."
-          .\windows_automation\data_type_finding.ps1
-        shell: pwsh  # Use PowerShell Core (pwsh)
+          run: |
+            write-host "PowerShell script invoked and is being executed..."
+            try {
+              .\windows_automation\data_type_finding.ps1
+            }
+            catch {
+              write-host "An error occurred: $_"
+              exit 1  # Ensure the job fails on error
+            }
+          shell: pwsh  # Use PowerShell Core (pwsh)
